## Q1. Pandas version
What's the version of Pandas that you installed?

In [66]:
import pandas as pd
pd.__version__

'2.3.2'

In [67]:
# get data from 
# wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

In [68]:
# check the data
df = pd.read_csv('data/car_fuel_efficiency.csv')
df.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. Records count
How many records are in the dataset?

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [70]:
df.shape

(9704, 11)

## Q3. Fuel types
How many fuel types are presented in the dataset?

In [71]:
df.fuel_type.nunique()

2

In [72]:
df.fuel_type.value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

## Q4. Missing values
How many columns in the dataset have missing values?

In [73]:
df.isnull().any().sum()

np.int64(4)

In [74]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?



In [75]:
df.origin.unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [76]:
asia_df = df[df.origin.str.lower() == 'asia']
result = asia_df.fuel_efficiency_mpg.max()

In [77]:
print(result)

23.759122836520497


## Q6. Median value of horsepower

1. Find the median value of horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?

* Yes, it increased
* Yes, it decreased
* No

In [78]:
# 1. Find the median value of horsepower column in the dataset.
df_hp_median = df.horsepower.median()
df_hp_median

np.float64(149.0)

In [79]:
# 2. Next, calculate the most frequent value of the same horsepower column.
df_hp_grouped = df.horsepower.value_counts()
df_hp_grouped

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [80]:
mfreq_value = df_hp_grouped.sort_values(ascending=False).index[0]
mfreq_value

np.float64(152.0)

In [81]:
# 3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df_hp_fillna = df_hp.fillna(mfreq_value)
df_hp_fillna.groupby(df_hp_fillna).agg(['count']).sort_values('count', ascending=False)


count
horsepower       
152.0         850
145.0         141
151.0         134
141.0         130
148.0         130
...           ...
231.0           1
245.0           1
246.0           1
252.0           1
271.0           1

[192 rows x 1 columns]

In [82]:
# 4. Now, calculate the median value of horsepower once again.
df_hp_fillna_median = df_hp_fillna.median()
df_hp_fillna_median

np.float64(152.0)

In [83]:
# Has it changed?
print('Horsepower Median:', df_hp_median)
print('Horsepower Median after fillna:', df_hp_fillna_median)

Horsepower Median: 149.0
Horsepower Median after fillna: 152.0


### Yes, it increased

## Q7. Sum of weights
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [84]:
# 1. Select all the cars from Asia
df_asia = df[df.origin.str.lower() == 'asia']
df_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [85]:
# 2. Select only columns vehicle_weight and model_year
df_asia_filtered = df_asia[['vehicle_weight', 'model_year']]
df_asia_filtered

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [86]:
# 3. Select the first 7 values
df_asia_filtered_7 = df_asia_filtered.head(7)
df_asia_filtered_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [87]:
# 4. Get the underlying NumPy array. Let's call it X.
X = df_asia_filtered_7.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [88]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.
XT = X.T
XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [89]:
# 6. Invert XTX.
import numpy as np

XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [90]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [91]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(XT).dot(y)
w

array([0.01386421, 0.5049067 ])

In [92]:

# 9. What's the sum of all the elements of the result?
result = w.sum()
print(result)

0.5187709081074016
